# Drone Pipeline
pipeline:
  build:
    image: node
    commands:
      - cd frontend
      - npm i redis --save
  test:
    image: node
    commands:
      - cd frontend
      - npm i redis --save
      - npm test
  publish:
    image: plugins/docker
    dockerfile: ./frontend/Dockerfile
    context: ./frontend
    repo: ashokshingade24/frontend
    tags: [latest, v1]
    secrets: [ docker_username, docker_password ]
  kubectl:
    image: dstrebel/drone-kubectl-helm
    secrets: [ kubernetes_server, kubernetes_cert, kubernetes_token ]
    kubectl: "apply -f ./frontend/deployment.yaml"

