# Drone Pipeline
pipeline:
  build:
    image: node
    commands:
      - cd frontend
      - npm i redis --save
  test:
    image: node
    commands:
      - cd frontend
      - npm i redis --save
      - npm test

